# Generated by Django 5.1.7 on 2025-06-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_employee_positive_leave_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='paid_dates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unpaid_dates',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
