# Generated by Django 5.1.7 on 2025-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_leaverequest_paid_dates_leaverequest_unpaid_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_credit_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
